export type StringIdsType = StringIds | StringIds[];

// List of StringIds
export enum StringIds {
  cABOUT_US = 'cABOUT_US',
  cADD_USER = 'cADD_USER',
  cAPPLY = 'cAPPLY',
  cBLOG = 'cBLOG',
  cCANCEL = 'cCANCEL',
  cCOMMUNICATION_ADDRESS = 'cCOMMUNICATION_ADDRESS',
  cCOURSENAME = 'cCOURSENAME',
  cCOURSES = 'cCOURSES',
  cEMAIL = 'cEMAIL',
  cENGLISH = 'cENGLISH',
  cFIRSTNAME = 'cFIRSTNAME',
  cGERMAN = 'cGERMAN',
  cHELLO = 'cHELLO',
  cHOME = 'cHOME',
  cJAPANESE = 'cJAPANESE',
  cLANGUAGE = 'cLANGUAGE',
  clASTNAME = 'cLASTNAME',
  cLOGIN = 'cLOGIN',
  cMOBILE1 = 'cMOBILE1',
  cMOBILE2 = 'cMOBILE2',
  cPASSWORD = 'cPASSWORD',
  cNO = 'cNO',
  cORGANIZATION = 'cORGANIZATION',
  cPERMANENT_ADDRESS = 'cPERMANENT_ADDRESS',
  cSPANISH = 'cSPANISH',
  cTOGGLE = 'cTOGGLE',
  cUSERNAME = 'cUSERNAME',
  cYES = 'cYES',
  cSIGNUP = 'cSIGNUP',
  cTODO_ID = 'Todo Id',
  cTODO_TITLE = 'Todo Title',
  cSTATUS = 'Status',
  cDESCRIPTION = 'Description',
  cDELETE = 'Delete',
  cUPDATE = 'Update',
  cADD_TODO = 'Add Todo',
  cUPDATE_TODO = 'Update Todo',
  cDUE_DATE = 'Due Date',
  cPENDING = 'Pending',
  cCOMPLETED = 'Completed',
}
