name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v3.21.2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libboost-all-dev \
          libgtest-dev \
          cmake \
          libssl-dev

    - name: Install nlohmann_json
      run: sudo apt-get install -y nlohmann-json3-dev

    - name: Build and run tests
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
        ctest --output-on-failure
